apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      # initContainers:
      # - name: volume-permissions
      #   image: busybox
      #   command: ["sh", "-c", "chown -R 1000:1000 /var/jenkins_home"]

      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
        - containerPort: 50000


